# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Config converter written in python

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        powershell.exe installResources.ps1
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build app with pyinstaller
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pyinstaller.exe --onefile program.py
    - uses: actions/upload_artifact@v3
	  with:
		name: my-artifact
		path: path/to/artifact/world.txt
    
